use std::fmt::Write as _;
use std::path::{Path, PathBuf};

const FIRST_CHAR: u32 = 32;
const LAST_CHAR: u32 = 126;

fn main() {
    let root = workspace_root();
    let ttf = std::fs::read(root.join("tools/fontgen/assets/SpaceGrotesk-Medium.ttf"))
        .expect("font asset missing");
    let font = fontdue::Font::from_bytes(ttf.as_slice(), fontdue::FontSettings::default())
        .expect("failed to parse font");

    std::fs::create_dir_all(root.join("kernel/assets")).unwrap();

    let mut out = String::from(
        "// Generated by `cargo run -p fontgen` from Space Grotesk Medium (OFL).\n// Do not edit by hand.\nuse super::text::{Font, GlyphMeta};\n",
    );
    out.push_str(&generate(&font, 28.0, "clock", &root));
    std::fs::write(root.join("kernel/src/gfx/font_data.rs"), out).unwrap();
    println!("wrote kernel/src/gfx/font_data.rs");
}

fn generate(font: &fontdue::Font, px: f32, name: &str, root: &Path) -> String {
    let lm = font.horizontal_line_metrics(px).expect("no horizontal metrics");
    let mut bitmap: Vec<u8> = Vec::new();
    let mut metas = String::new();
    let mut digit_advance: i16 = 0;

    for cp in FIRST_CHAR..=LAST_CHAR {
        let c = char::from_u32(cp).unwrap();
        let (m, bm) = font.rasterize(c, px);
        let offset = bitmap.len();
        bitmap.extend_from_slice(&bm);
        let advance = m.advance_width.round() as i16;
        if c.is_ascii_digit() {
            digit_advance = digit_advance.max(advance);
        }
        writeln!(
            metas,
            "        GlyphMeta {{ xmin: {}, ymin: {}, w: {}, h: {}, advance: {}, offset: {} }},",
            m.xmin, m.ymin, m.width, m.height, advance, offset
        )
        .unwrap();
    }

    let bin = format!("font_{name}.bin");
    std::fs::write(root.join("kernel/assets").join(&bin), &bitmap).unwrap();
    println!("wrote kernel/assets/{bin} ({} bytes, {} glyphs)", bitmap.len(), LAST_CHAR - FIRST_CHAR + 1);

    format!(
        "\npub static FONT_{}: Font = Font {{\n    first_char: {},\n    glyphs: &[\n{}    ],\n    bitmap: include_bytes!(\"../../assets/{}\"),\n    ascent: {},\n    descent: {},\n    line_height: {},\n    digit_advance: {},\n}};\n",
        name.to_uppercase(),
        FIRST_CHAR,
        metas,
        bin,
        lm.ascent.round() as i16,
        lm.descent.round() as i16,
        lm.new_line_size.round() as i16,
        digit_advance
    )
}

fn workspace_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .to_path_buf()
}
